/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Blogcard = {
  _id: string;
  _type: "blogcard";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  card?: Array<{
    backgroundImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    heading?: Array<{
      headingTitle?: string;
      headingDescription?: string;
      _type: "headingItem";
      _key: string;
    }>;
    mainDescription?: string;
    image?: Array<{
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "imageitem";
      _key: string;
    }>;
    mainComment?: string;
    blog?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "Blogs";
    };
    _type: "item";
    _key: string;
  }>;
};

export type Card = {
  _id: string;
  _type: "card";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  cardItem?: Array<{
    title?: string;
    image?: Array<{
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "imageitem";
      _key: string;
    }>;
    description?: string;
    blog?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "Blogs";
    };
    _type: "item";
    _key: string;
  }>;
};

export type Blogs = {
  _id: string;
  _type: "Blogs";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  BlogTitle?: string;
};

export type Presentation = {
  _id: string;
  _type: "presentation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  items?: Array<{
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    title?: string;
    description?: string;
    _type: "presentationItem";
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes = Blogcard | Card | Blogs | Presentation | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityImageAsset | SanityImageMetadata | Geopoint | Slug | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./app/components/blog/home.tsx
// Variable: blogDetailsQue
// Query: *[_type == "blogcard"][0].card[blog->BlogTitle==$blogUrl || blog->slug.current match $blogUrl][0]{  ...,  "blog":blog->}
export type BlogDetailsQueResult = {
  backgroundImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  heading?: Array<{
    headingTitle?: string;
    headingDescription?: string;
    _type: "headingItem";
    _key: string;
  }>;
  mainDescription?: string;
  image?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "imageitem";
    _key: string;
  }>;
  mainComment?: string;
  blog: {
    _id: string;
    _type: "Blogs";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    BlogTitle?: string;
  } | null;
  _type: "item";
  _key: string;
} | null;
// Variable: blogDetailsQuery
// Query: *[_type == "blogcard"][0].card[blog->BlogTitle == $blogUrl || blog->slug.current match $blogUrl]{  ...,  "blog": blog->}
export type BlogDetailsQueryResult = Array<{
  backgroundImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  heading?: Array<{
    headingTitle?: string;
    headingDescription?: string;
    _type: "headingItem";
    _key: string;
  }>;
  mainDescription?: string;
  image?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "imageitem";
    _key: string;
  }>;
  mainComment?: string;
  blog: {
    _id: string;
    _type: "Blogs";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    BlogTitle?: string;
  } | null;
  _type: "item";
  _key: string;
}> | null;

// Source: ./app/components/presentations.tsx
// Variable: fetchDetailsQuery
// Query: *[_type=="presentation"][0]
export type FetchDetailsQueryResult = {
  _id: string;
  _type: "presentation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  items?: Array<{
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    title?: string;
    description?: string;
    _type: "presentationItem";
    _key: string;
  }>;
} | null;

// Source: ./app/pages/ChartPresentation.tsx
// Variable: fetchBlogDetailsQuery
// Query: *[_type=='card']{  cardItem[]{    ...,    "blog":blog->  }}
export type FetchBlogDetailsQueryResult = Array<{
  cardItem: Array<{
    title?: string;
    image?: Array<{
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "imageitem";
      _key: string;
    }>;
    description?: string;
    blog: {
      _id: string;
      _type: "Blogs";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      BlogTitle?: string;
    } | null;
    _type: "item";
    _key: string;
  }> | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type == \"blogcard\"][0].card[blog->BlogTitle==$blogUrl || blog->slug.current match $blogUrl][0]{\n  ...,\n  \"blog\":blog->\n}": BlogDetailsQueResult;
    "*[_type == \"blogcard\"][0].card[blog->BlogTitle == $blogUrl || blog->slug.current match $blogUrl]{\n  ...,\n  \"blog\": blog->\n}": BlogDetailsQueryResult;
    "*[_type==\"presentation\"][0]": FetchDetailsQueryResult;
    "*[_type=='card']{\n  cardItem[]{\n    ...,\n    \"blog\":blog->\n  }\n}": FetchBlogDetailsQueryResult;
  }
}
